const CLIENT_ID="795262990945-lr75dt13cai408qcn33o3bf6di644r5n.apps.googleusercontent.com";
const SCOPE="https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/calendar.events";
const FILE_NAME="personal-os-v1.json";let token=null,fileId=null,timer=null;let state;try{state=JSON.parse(localStorage.getItem("personalOSv1"))||{tasks:[]}}catch{state={tasks:[]}}state.tasks||=[];const $=s=>document.querySelector(s);$("#today").textContent=new Intl.DateTimeFormat("ko-KR",{dateStyle:"full"}).format(new Date());
function render(){const box=$("#taskList");box.innerHTML="";for(const t of [...state.tasks].sort((a,b)=>Number(a.done)-Number(b.done)||(b.updatedAt||"").localeCompare(a.updatedAt||""))){const row=document.createElement("div");row.className="task"+(t.done?" done":"");const cb=document.createElement("input");cb.type="checkbox";cb.checked=!!t.done;cb.onchange=()=>{t.done=cb.checked;t.updatedAt=new Date().toISOString();saveLocal()};const txt=document.createElement("div");txt.className="taskText";txt.textContent=t.text;const del=document.createElement("button");del.className="delete";del.textContent="×";del.onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);saveLocal()};row.append(cb,txt,del);box.append(row)}$("#count").textContent=state.tasks.filter(t=>!t.done).length}
function saveLocal(){localStorage.setItem("personalOSv1",JSON.stringify(state));render();if(token){clearTimeout(timer);timer=setTimeout(()=>saveCloud().catch(syncError),600)}}$("#taskForm").onsubmit=e=>{e.preventDefault();const v=$("#taskInput").value.trim();if(!v)return;state.tasks.push({id:crypto.randomUUID(),text:v,done:false,updatedAt:new Date().toISOString()});$("#taskInput").value="";saveLocal()};
async function request(url,opts={}){opts.headers={...(opts.headers||{}),Authorization:`Bearer ${token}`};const r=await fetch(url,opts);if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);if(r.status===204)return null;return r.json()}
function merge(a,b){const m=new Map;for(const t of [...(b.tasks||[]),...(a.tasks||[])]){const old=m.get(t.id);if(!old||(t.updatedAt||"")>(old.updatedAt||""))m.set(t.id,t)}return{schemaVersion:1,tasks:[...m.values()],updatedAt:new Date().toISOString()}}
async function findFile(){const q=encodeURIComponent(`name='${FILE_NAME}' and trashed=false`);const x=await request(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${q}&fields=files(id)`);return x.files?.[0]||null}
async function createFile(){const boundary="pos_"+Date.now(),metadata=JSON.stringify({name:FILE_NAME,parents:["appDataFolder"],mimeType:"application/json"}),body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(state)}\r\n--${boundary}--`;const x=await request("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id",{method:"POST",headers:{"Content-Type":`multipart/related; boundary=${boundary}`},body});fileId=x.id}
async function loadCloud(){const f=await findFile();if(!f)await createFile();else{fileId=f.id;const cloud=await request(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`);state=merge(state,cloud);localStorage.setItem("personalOSv1",JSON.stringify(state));render();await saveCloud()}}
async function saveCloud(){if(!token||!fileId)return;state.updatedAt=new Date().toISOString();await request(`https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(state)});$("#sync").textContent="Drive + Calendar 연결됨"}
function eventTime(e){if(e.start?.date)return e.start.date+" · 종일";const s=new Date(e.start.dateTime),en=new Date(e.end.dateTime);return new Intl.DateTimeFormat("ko-KR",{month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(s)+" ~ "+new Intl.DateTimeFormat("ko-KR",{hour:"2-digit",minute:"2-digit"}).format(en)}
async function loadEvents(){if(!token)return;$("#events").innerHTML='<div class="empty">Calendar 불러오는 중…</div>';const min=new Date(),max=new Date();max.setDate(max.getDate()+14);const u="https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=50&timeMin="+encodeURIComponent(min.toISOString())+"&timeMax="+encodeURIComponent(max.toISOString());const x=await request(u),box=$("#events");box.innerHTML="";if(!x.items?.length){box.innerHTML='<div class="empty">향후 14일 일정이 없습니다.</div>';return}for(const e of x.items){const row=document.createElement("div");row.className="event";const main=document.createElement("div");main.className="eventMain";const tm=document.createElement("div");tm.className="eventTime";tm.textContent=eventTime(e);const tt=document.createElement("div");tt.className="eventTitle";tt.textContent=e.summary||"(제목 없음)";main.append(tm,tt);const del=document.createElement("button");del.className="delete";del.textContent="×";del.title="Google Calendar에서 삭제";del.onclick=async()=>{if(!confirm(`'${e.summary||"일정"}' 일정을 Google Calendar에서 삭제할까요?`))return;await request(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(e.id)}`,{method:"DELETE"});await loadEvents()};row.append(main,del);box.append(row)}}
$("#eventForm").onsubmit=async e=>{e.preventDefault();if(!token)return alert("먼저 Google 연결을 눌러주세요.");const title=$("#eventTitle").value.trim(),start=$("#eventStart").value,end=$("#eventEnd").value;if(!title||!start||!end)return;if(new Date(end)<=new Date(start))return alert("종료 시간은 시작 시간보다 뒤여야 합니다.");await request("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({summary:title,start:{dateTime:new Date(start).toISOString(),timeZone:"Asia/Seoul"},end:{dateTime:new Date(end).toISOString(),timeZone:"Asia/Seoul"}})});$("#eventTitle").value="";await loadEvents()};$("#refreshCal").onclick=()=>loadEvents().catch(syncError);
function syncError(e){console.error(e);$("#sync").textContent="연결 오류 · Google 권한/설정을 확인하세요"}
$("#googleBtn").onclick=()=>{if(!window.google?.accounts?.oauth2)return alert("Google 로그인 모듈을 불러오는 중입니다. 잠시 후 다시 눌러주세요.");const tc=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,include_granted_scopes:true,callback:async r=>{if(r.error)return syncError(r);token=r.access_token;$("#googleBtn").textContent="Google 연결됨";try{await loadCloud();await loadEvents();$("#sync").textContent="Drive + Calendar 연결됨"}catch(e){syncError(e)}}});tc.requestAccessToken({prompt:"consent"})};
function defaultTimes(){const s=new Date();s.setMinutes(Math.ceil(s.getMinutes()/30)*30,0,0);const e=new Date(s.getTime()+3600000),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$("#eventStart").value=local(s);$("#eventEnd").value=local(e)}render();defaultTimes();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");